const morningQuotes = [
  "🌅 Good morning! Every sunrise is a new opportunity to become a better version of yourself.",
  "☀️ Rise and shine! Small progress every day leads to big results.",
  "💪 Start today with purpose, positivity, and determination.",
  "✨ Good morning! Today is another chance to chase your goals.",
  "🚀 Wake up. Stay focused. Make today count.",

  "🌞 A fresh morning brings fresh possibilities. Make the most of them.",
  "☕ Start your day with confidence and let your actions speak.",
  "🌤️ Every morning is a reminder that you have another chance.",
  "📖 Today is a blank page—write a story you'll be proud of.",
  "🌻 Wake up with gratitude, work with passion.",
  "🔥 Your future is built by what you do today.",
  "💡 Believe in yourself before anyone else does.",
  "🎯 Focus on progress, not excuses.",
  "🌈 A positive mindset creates positive outcomes.",
  "🚴 Every step forward is a step closer to success.",
  "🌸 Smile. Today is full of opportunities waiting for you.",
  "🏆 Success starts with showing up.",
  "🌼 Let your determination be stronger than your doubts.",
  "✨ Don't wait for motivation—create it.",
  "📈 Make today better than yesterday.",
  "🚀 Consistency beats perfection every time.",
  "🌅 The best time to start is now.",
  "💪 Great things begin with a single decision to try.",
  "☀️ You've got everything you need to make today amazing.",
  "🌟 Wake up inspired and leave a positive impact.",
];

const afternoonQuotes = [
  "☀️ Good afternoon! Stay productive—you're capable of amazing things.",
  "💻 Keep going. Success is built one step at a time.",
  "🔥 Don't lose momentum. The day isn't over yet.",
  "🎯 Stay focused. Every task completed gets you closer to your goals.",
  "⚡ Progress, not perfection.",

  "🌤️ Half the day is gone—make the rest count.",
  "🚀 Keep pushing. Your future self will thank you.",
  "💡 Every effort you make today matters.",
  "📚 Stay curious and keep learning.",
  "🌞 Don't let a slow start define your finish.",
  "🏃 You're stronger than your excuses.",
  "✨ Stay disciplined even when motivation fades.",
  "🎯 Success belongs to those who refuse to quit.",
  "🔥 Keep your goals bigger than your fears.",
  "📈 Small improvements create extraordinary results.",
  "🌻 Focus on what you can control.",
  "💪 Your hard work is creating opportunities.",
  "⚡ Keep moving forward, even if it's one step at a time.",
  "🌟 Every productive afternoon brings you closer to your dreams.",
  "🛠️ Build your future with today's effort.",
  "☕ Take a short break, then come back stronger.",
  "🚴 Momentum grows with every completed task.",
  "🎉 Celebrate progress, then aim even higher.",
  "📖 Learn something new before the day ends.",
  "🌈 Finish today with pride.",
];

const eveningQuotes = [
  "🌇 Good evening! Take a moment to appreciate how far you've come today.",
  "🌆 Reflect on today's wins, no matter how small.",
  "🍃 Every sunset reminds us tomorrow is another opportunity.",
  "🌟 Rest doesn't mean giving up—it prepares you for tomorrow.",
  "✨ Great work today. Keep moving forward.",

  "🌅 Every evening is proof that you made it through another day.",
  "📖 Reflect, learn, and grow from today's experiences.",
  "🍂 Let go of today's worries and embrace tomorrow's opportunities.",
  "🌠 Be proud of every step you took today.",
  "💪 Success is built through consistent effort.",
  "🕯️ Find peace in the progress you've made.",
  "🌌 The work you did today matters.",
  "🌙 Take a deep breath—you've earned it.",
  "🌿 End the day with gratitude.",
  "⭐ Every ending is a new beginning in disguise.",
  "🏡 Home is where you recharge your strength.",
  "☕ Slow down and enjoy the quiet moments.",
  "🎯 Review your goals and prepare for tomorrow.",
  "📈 Every day teaches something valuable.",
  "💡 Celebrate your effort, not just the outcome.",
  "🌻 Growth happens one day at a time.",
  "✨ Be kind to yourself—you did your best.",
  "🍁 Peace comes from appreciating the present.",
  "🚶 Tomorrow starts with how you end today.",
  "🌠 Rest your mind and keep your dreams alive.",
];

const nightQuotes = [
  "🌙 Good night! Rest well and recharge for another successful day.",
  "😴 Sleep is the best investment you can make for tomorrow.",
  "⭐ End the day with gratitude and peace.",
  "🌌 Every day ends, but every tomorrow begins with new opportunities.",
  "💤 Good night. Dream big, rest well.",

  "🌙 Let your worries rest with the setting moon.",
  "🌠 Sleep peacefully knowing you gave today your best.",
  "✨ Tomorrow holds another chance to succeed.",
  "🌌 Close your eyes and welcome peaceful dreams.",
  "💫 Every night is a fresh reset.",
  "🌃 Rest is part of the journey to success.",
  "🛏️ Recharge your body and your mind.",
  "⭐ Good night. Believe in the future you're building.",
  "🌙 Peace begins with letting go.",
  "🌠 Sleep with hope, wake with purpose.",
  "🌌 Every star reminds us to keep dreaming.",
  "💤 A rested mind makes wiser decisions.",
  "🌿 Relax. Tomorrow is another opportunity to shine.",
  "🕊️ Leave today's stress behind.",
  "✨ Rest is productive too.",
  "🌙 End today with gratitude and optimism.",
  "⭐ Your dreams today become your goals tomorrow.",
  "🌠 May your sleep be peaceful and your tomorrow successful.",
  "💫 Good night. Better days are always ahead.",
  "🌌 Sleep well and wake up ready to conquer another day.",
];

module.exports = {
  morningQuotes,
  afternoonQuotes,
  eveningQuotes,
  nightQuotes,
};
